### ISSUE TITLE
Docker command missing

### ISSUE THREAD

**Issue by nekator** [jfrog/jfrog-ecosystem-integration-env#19]
jfrog-cli uses docker command for some container operations. All jfrog-cli commands which require docker will fail using the jfrog-cli-full-v2 image.

As podman is already available inside the image podman could be used instead of docker.
`RUN ln -s /usr/bin/podman /usr/bin/docker`

**Comment by yahavi** [comment]
@nekator,
Thanks for reporting this issue.
Collecting the build-info whereby the "docker" is a soft link to "podman" probably won't work.

However, the JFrog CLI already support the pull and push Podman commands:
```
jf rt podman-pull
jf rt podman-push
```

For more information see [Managing Docker Images](https://www.jfrog.com/confluence/display/CLI/CLI+for+JFrog+Artifactory#CLIforJFrogArtifactory-ManagingDockerImages).

Please let me know what do you think.

**Comment by nekator** [comment]
I have problems to scan container images via jfrog-cli because the scan uses docker save which could also be done by podman save. So I thought a quick fix would be link docker to pod man inside the Image.

Alternatively I could think about something like a additional command or some configuration to use podman instead of docker for the cli.

**Comment by yahavi** [comment]
Thanks for your input.
We think that the right place to add this feature is to add a `podman scan` command in the JFrog CLI.
Running docker scan with Podman is not expected to work.

Could you please create a feature request for `jf podman scan` command in the JFrog CLI?
https://github.com/jfrog/jfrog-cli/issues/new/choose

**Comment by nekator** [comment]
I will create a feature request in JFrog CLI for this.
Thanks for the fast reply
